### ISSUE TITLE
No issue: your username is awesome

### ISSUE THREAD

**Issue by ghost** [magcho/Tsukushi#1]
I really like your username, man. I didn't know how to privately message you, so here I am.

**Comment by magcho** [comment]
Thank you. 
This name is influenced by this book. 
[amazon](https://www.amazon.co.jp/%E4%B8%96%E7%95%8C%E4%B8%80%E3%81%8A%E3%81%84%E3%81%97%E3%81%84%E7%81%AB%E5%B1%B1%E3%81%AE%E6%9C%AC%E2%80%95%E3%83%81%E3%83%A7%E3%82%B3%E3%82%84%E3%82%B3%E3%82%B3%E3%82%A2%E3%81%A7%E5%99%B4%E7%81%AB%E5%AE%9F%E9%A8%93-%E8%87%AA%E7%84%B6%E3%81%A8%E3%81%A8%E3%82%82%E3%81%AB-%E6%9E%97-%E4%BF%A1%E5%A4%AA%E9%83%8E/dp/4338186089)
This book title is "世界一おいしい火山の本". It mean "The volcano book the most delicious in the world. "

Please forgive me my lousy English.
